### ISSUE TITLE
Version 4.1.1 does not work in 2.18 built by homebrew on Mac OS 10.9

### ISSUE THREAD

**Issue by cbertelli** [PANOimagen/profiletool#3]
Hello,
the title says almost all, QGIS says "The plugin is corrupt"
The error is: "cannot import name uic".

**Comment by JaviBecerra** [comment]
Hi @cbertelli,
We do not have a mac platform to check this at the moment; I found an issue similar to yours in https://github.com/OSGeo/homebrew-osgeo4mac/issues/264 where it seems that the problem laid in the way Qgis was launched. Could you check on that and let us know if that helped?

**Comment by JaviBecerra** [comment]
Hi @cbertelli,
I am closing this issue cause we can not reproduce it and have not had any additional feedback on your side.
Please do not doubt to reopen the issue if it persists for you, but please provide us with some additional information so that we can try to reproduce it.
Regards,
Javier
